// File: src/ai/flows/generate-product-description.ts
'use server';

/**
 * @fileOverview This file defines a Genkit flow for generating compelling product descriptions using Gemini AI.
 *
 * It includes:
 * - `generateProductDescription`:  A function that orchestrates the product description generation process.
 * - `GenerateProductDescriptionInput`: The schema for the input to the `generateProductDescription` function, including product name and details.
 * - `GenerateProductDescriptionOutput`: The schema for the output of the `generateProductDescription` function, which is the generated product description.
 */

import {ai} from '@/ai/genkit';
import {z} from 'genkit';

const GenerateProductDescriptionInputSchema = z.object({
  productName: z.string().describe('The name of the product.'),
  productDetails: z.string().describe('Detailed information about the product, including features, materials, and benefits.'),
});
export type GenerateProductDescriptionInput = z.infer<typeof GenerateProductDescriptionInputSchema>;

const GenerateProductDescriptionOutputSchema = z.object({
  productDescription: z.string().describe('A compelling and engaging product description generated by Gemini AI.'),
});
export type GenerateProductDescriptionOutput = z.infer<typeof GenerateProductDescriptionOutputSchema>;

export async function generateProductDescription(
  input: GenerateProductDescriptionInput
): Promise<GenerateProductDescriptionOutput> {
  return generateProductDescriptionFlow(input);
}

const productDescriptionPrompt = ai.definePrompt({
  name: 'productDescriptionPrompt',
  input: {schema: GenerateProductDescriptionInputSchema},
  output: {schema: GenerateProductDescriptionOutputSchema},
  prompt: `You are an expert copywriter specializing in creating compelling product descriptions.

  Based on the product name and details provided, write an engaging and informative product description that will attract customers and improve listings.

  Product Name: {{{productName}}}
  Product Details: {{{productDetails}}}

  Product Description:`, // Ensure the model generates only the description
});

const generateProductDescriptionFlow = ai.defineFlow(
  {
    name: 'generateProductDescriptionFlow',
    inputSchema: GenerateProductDescriptionInputSchema,
    outputSchema: GenerateProductDescriptionOutputSchema,
  },
  async input => {
    const {output} = await productDescriptionPrompt(input);
    return output!;
  }
);
